Updated to the new image server.
evekb/evedev-kb pull request #112
Opened 2019-11-16 22:09 UTC by StinGer-ShoGuN

Actually, this is more of a 'hack' than a real fix. I'm saying this because maybe, the way images are handled should be reviewed; I don't know the sources enough to tell.

It might be incomplete. I'll update it if necessary.

See https://developers.eveonline.com/blog/article/from-image-server-to-a-whole-new-image-service-1 for details.

2019-11-23 19:47 UTC, Salvoxia requested changes
I made two change suggestions so that the URL is constructed correctly for character portraits and alliance/corporation logos.
Also, the following change is required for corp logos to be fetched:
[Line 195 of common/includes/class.thumb.php](https://github.com/evekb/evedev-kb/pull/112/files#diff-06710fbcf49b8258e6372cd529bd2f16R195) needs to be 
`$img = $this->fetchImage('corp', 128);`

Could you please incorporate these changes, then I'll merge the changes.

2019-11-23 19:47 UTC, Salvoxia commented on common/includes/class.thumb.php
> +            $url .= "portrait?size=${size}";
Needs to start with a slash to build the URL correctly:
```suggestion
            $url .= "/portrait?size=${size}";
```

2019-11-23 19:47 UTC, Salvoxia commented on common/includes/class.thumb.php
> +            $url .= "logo?size=${size}";
Needs to start with a slash to build the URL correctly:
```suggestion
            $url .= "/logo?size=${size}";
```

2019-11-24 09:12 UTC, StinGer-ShoGuN commented
Nice catch !

Where are thumbs used in the KB ? Because I didn't see any errors (404) on mine...

2019-11-26 17:04 UTC, merged

2019-11-26 18:42 UTC, Salvoxia commented
Thank you very much for your contribution!
Do you know what's up with some of the NPC logos on the new image server?
The Faction "Unknown" does not have a logo, even though most of the other factions do:
https://images.evetech.net/corporations/500021/logo
vs.
https://images.evetech.net/corporations/500026/logo

Same for Drifters:
https://images.evetech.net/corporations/1000274/logo

2019-11-26 22:34 UTC, StinGer-ShoGuN commented
I have no idea... Digging a bit I realised the server returns a 404 on those with a x-cache error "Error from cloudfront". Maybe it's an issue from CCP CDN.

I've posted [a message](https://forums.eveonline.com/t/new-image-server-again/202922) on EVE forums. Maybe we'll have an answer.

2019-11-26 23:58 UTC, soratidus999 commented
There are many issues with the new image server currently.  Many alliance logos have been available/unavailable at various times over the last several weeks